version: 0.2

phases:
  build:
    commands:
      # Build the project
      - mvn package
      # Package SAM template
      - sam package --template-file sam-template.yaml --s3-bucket todo-app-java-build --output-template-file sam-template-output.yaml
      
      # Deploy packaged SAM template
      - sam deploy --region us-east-2 --template-file sam-template-output.yaml --stack-name todo-app --capabilities CAPABILITY_IAM

cache:
  paths:
    - '/root/.m2/**/*'

artifacts:
  files:
    - sam-template-output.yaml
    - config-*.json
